### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by 0312birdzhang** [SUSE/saltstack-netapi-client-java#98]
Some test code 
```java
		 URI uri = URI.create(saltapiurlString);

		 SaltStackClient client = new SaltStackClient(uri);
        try {
			Token token = client.login(saltuser, saltpassword, AuthModule.PAM);
			System.out.println(token.getToken());
			List<String> param = new ArrayList<>();
```
I can use 
```bash
[birdzhang@myhost:salt]$ curl -k http://192.168.0.72:8000/login -H "Accept: application/x-yaml" -d username='ops' -d password='ops' -d eauth='pam'
return:
- eauth: pam
  expire: 1440012727.2649801
  perms:
  - .*
  - '@runner'
  - '@wheel'
  start: 1439969527.2649801
  token: ecbd8f11d469ddafa1c91fb97cad343b3b931d65
  user: ops

```
Console log:
```java
com.suse.saltstack.netapi.exception.SaltStackException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.suse.saltstack.netapi.client.impl.HttpClientConnection.request(HttpClientConnection.java:87)
	at com.suse.saltstack.netapi.client.impl.HttpClientConnection.getResult(HttpClientConnection.java:65)
	at com.suse.saltstack.netapi.client.SaltStackClient.login(SaltStackClient.java:133)
	at com.gomo.test.CheckSaltClient.main(CheckSaltClient.java:34)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:279)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:273)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1469)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:837)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.suse.saltstack.netapi.client.impl.HttpClientConnection.executeRequest(HttpClientConnection.java:188)
	at com.suse.saltstack.netapi.client.impl.HttpClientConnection.request(HttpClientConnection.java:85)
	... 3 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1451)
	... 24 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 30 more
```

**Comment by renner** [comment]
Hey @0312birdzhang, what is the `saltapiurlString` you are using in your test code? Does it start with `https://`? Usually this exception means that java wants to connect via SSL, but the target server's CA certificate is missing in Java's truststore.

As a solution to this you should add the certificate to the truststore which can be done using [Java's keytool] (https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html). Alternatively you can always fallback to use unencrypted `http://`, but I would not recommend it for prodcution usage.

**Comment by 0312birdzhang** [comment]
@renner Yeah,it start with<code>https://</code>,I had add<code>disable_ssl: true</code>to my conf file.
I will try to add the certificate,thank you.
So,it's not an issue,i will close it.
